[workspace]
members = ["examples/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.76"
authors = ["Alloy Contributors"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/alloy-rs/examples"
repository = "https://github.com/alloy-rs/examples"
publish = false
exclude = ["examples/"]

[workspace.dependencies]
alloy-consensus = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-contract = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-eips = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-genesis = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-json-rpc = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-network = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-node-bindings = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-provider = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-pubsub = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-rpc-client = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-rpc-engine-types = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-rpc-trace-types = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-serde = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-signer = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-signer-aws = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-signer-gcp = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-signer-ledger = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-signer-trezor = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-signer-wallet = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-transport = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-transport-http = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-transport-ipc = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }
alloy-transport-ws = { git = "https://github.com/alloy-rs/alloy", rev = "e7dfb4f", default-features = false }

alloy-core = { version = "0.6.4", default-features = false, features = ["std"] }
alloy-dyn-abi = { version = "0.6.4", default-features = false, features = [
    "std",
] }
alloy-json-abi = { version = "0.6.4", default-features = false, features = [
    "std",
] }
alloy-primitives = { version = "0.6.4", default-features = false, features = [
    "std",
] }
alloy-sol-types = { version = "0.6.4", default-features = false, features = [
    "std",
] }

# async
tokio = "1"

# misc
eyre = "0.6.12"
reqwest = { version = "0.11", default-features = false }

## serde
serde = { version = "1.0", features = ["derive"] }

[patch.crates-io]
alloy-core = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-dyn-abi = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-json-abi = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-primitives = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-sol-macro = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
alloy-sol-types = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
syn-solidity = { git = "https://github.com/alloy-rs/core", rev = "907d61a45a9135e979310990744080eef5f03fe5" }
